services:
  - type: web
    name: fullstack-mastery
    env: node
    rootDir: backend
    buildCommand: pnpm install --frozen-lockfile
                  pnpm run build
    startCommand: pnpm start
    autoDeploy: true
